# Generated by Django 3.0.7 on 2020-06-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigneeId',
        ),
        migrations.RemoveField(
            model_name='task',
            name='projectId',
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[(1, 'To Do'), (2, 'In Progress'), (3, 'Done')], default='To Do', max_length=15),
        ),
    ]
