# Generated by Django 3.0.7 on 2020-07-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronos', '0002_auto_20200703_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='totalTime',
            field=models.FloatField(null=True),
        ),
    ]
