# Generated by Django 3.0.7 on 2020-06-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronos', '0002_auto_20200608_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
